### ISSUE TITLE
global can find but ggtags cannot find

### ISSUE THREAD

**Issue by realwhz** [leoliu/ggtags#104]
Hello.

I found a weird issue on a Linux machine when I sshed to it.

Let's say I have a directory contains two files: a.c and a.h.  After running gtags, GPATH, GRTAGS, and GTAGS are generated.  Then, I launch emacs -nw and enable ggtags-mode.

ggtags cannot really find anything.  For example, ggtags-find-file always returns "Global found 0 matches".  However, manually running global can get the result:
$global -v --result=grep --path-style=shorter --path -- "a.c"
a.c:1:
1 file located (using '/tmp/tmp/GPATH').

or $global -P a.c
a.c

Can you please suggest a way to further debug?  I am using global 6.5.

Thank you.

**Comment by realwhz** [comment]
As an experiment, I tried the gtags.el shipped with global 6.5, it can work.

Thanks.

**Comment by realwhz** [comment]
Update.  Looks like emacs itself has some problems when issuing shell command.  For example, even M-! date returns (Shell command succeeded with no output)

**Comment by leoliu** [comment]
@realwhz,

Thanks for the report.

Could you try to verify if emacs is working properly? For example, `M-x shell` then repeat your `global` experiment in it? Does it work?

Leo

**Comment by realwhz** [comment]
Hi Leo,

In emacs, under M-x shell, global command successfully get the file, just the same as what I got under normal shell.

As I mentioned, I feel my emacs has some problems when accessing buffer contents.  For example, both M-! and M-| do not work properly.  I am still debugging it.

Thanks.

**Comment by realwhz** [comment]
Update:

The issue is fixed.  It proves to be an issue with my shell configuration.  The admin sets the default shell to tcsh and I accidentally put "exec /bin/bash --login" at the end of ~/.cshrc to automatically switch to bash.  Somehow this causes the problem I reported.  Now I moved this line into ~/.login and the issue is gone.

Thanks.
