### ISSUE TITLE
Ggtags cannot find tag, Global can

### ISSUE THREAD

**Issue by egarrulo** [leoliu/ggtags#108]
As an exercise to learn how to use Ggtags, I copied the standard C header files into a directory and then I run `gtags -c`. To check that everything worked, I run `global -xs strcmp` and Global answered:

    strcmp            144 string.h         extern int strcmp (const char *__s1, const char *__s2)

Then I created (with Emacs) a `test.c` file in the same directory.  When I typed the symbol `strcmp` and clicked on *Main Menu -> Ggtags -> Find Tag*, Ggtags said "Global found 0 definitions".  So, I opened a shell from Emacs into the same directory, and run `global -xs strcmp` again.  Again, Global answered:
    
    strcmp            144 string.h         extern int strcmp (const char *__s1, const char *__s2)

Why can't Ggtags find a tag, when Global can?  Thanks for your assistance.

**Comment by egarrulo** [comment]
I forgot to mention that I am using Linux.  I copied the standard C headers like this:

    mkdir c-headers
    cd c-headers
    cp /usr/include/*.h .

My understanding is that Ggtags can only lookup definitions, while Global lets you lookup declarations as well.

**Comment by leoliu** [comment]
Hi @egarrulo,

`ggtags` is only a convenience front-end to `global`. The problem is `global -xs` finds symbols, which is equivalent to `C-c M-o` in `ggtags`.

HTH,
Leo

**Comment by egarrulo** [comment]
Thank you for the clarification.  I am new to Global and even if I have read its manual, the manual uses an abstract nomenclature and I still don't understand what tags and symbols mean in a C++ context. Anyway, right now, my understanding is that Ggtags offers different keyboard shortcuts -- based on `global` commands -- to lookup either a definition, or a declaration, or all places where a symbol is referenced, right?  In this case, would it be possible to have a command in Ggtags that would jump to a definition if it is available, otherwise it would jump to a declaration?  This is because if you follow a symbol that you know is inside the project, most likely you want to see its implementation; whilst if you click on a symbol that you know it is imported from a library, most likely you just want to see its declaration.  Thanks for your attention.

**Comment by egarrulo** [comment]
Never mind.  The standard `find-tag` -- with a tag table generated by Exuberant Ctags -- does exactly what I want and, moreover, finds declarations that Global doesn't see.  Therefore, I recommend using `find-tag` to find symbols, and Ggtags to find references.

**Comment by gthaker** [comment]
Can this really be so that for C language excuberant tags finds  more entries than gtags does? Which type of entries are these?

**Comment by egarrulo** [comment]
> Can this really be so that for C language excuberant tags finds more entries than gtags does?

Of course, I wasn't implying that this was a fault of Ggtags.  By the way, I have used Pygments as the back-end to `gtags` (this is recommended by the documentation of Ggtags). 

> Which type of entries are these?

They are functions from the X11 library ("XFree", "XSync", etc.).  Global finds some of these functions, but not all of them.

**Comment by leoliu** [comment]
In global, there are three types of tags, `definitions`, `references` and `symbols`. When using `ctags` you only get `definitions`. It is possible that `ctags` finds more (definition) tags in `C` than `global`'s builtin parsers.

**Comment by egarrulo** [comment]
Yes, I had reached the same conclusion.  It seems that -- for C -- Exuberant Ctags is better than Pygments.  I will check whether indeed this is the case.  Maybe -- for C -- you'd better maintain two Global databases: one generated with Exuberant Ctags, for definitions and symbols; and the other generated with Pygments for references; and then advice Ggtags commands to select one of the other, depending on what you need.

**Comment by egarrulo** [comment]
Never mind.  Using Global with Exuberant Ctags does not solve the issue. By the way, Global feels difficult to use correctly.  Even with the `--verbose` option, `gtags` does not show much useful information in regard to what it is doing.  Anyway, thanks for your help.

**Comment by egarrulo** [comment]
Anyway, we have determined that this is not a problem of Ggtas, but of Global.  Therefore I vote to close this issue.  Thanks.
