### ISSUE TITLE
Prevent RET from exiting navigation mode

### ISSUE THREAD

**Issue by lindsayad** [leoliu/ggtags#113]
I'm sure there's an easy way to do this, but I'm still relatively new to emacs... Is there a way to set-up my ggtags so that when I enter RET in another buffer, the navigation menu stays up?

**Comment by leoliu** [comment]
Hi @lindsayad,

Maybe something along these lines

```
(require 'ggtags)
(define-key ggtags-navigation-map "\r" nil)
(define-key ggtags-navigation-map "\C-c\C-c" 'ggtags-navigation-mode-done)
```

HTH,
Leo

**Comment by lindsayad** [comment]
Awesome, with a little variation that worked great. (Since I'm working 
in the emacs gui, I used <return> instead of \r)

Alex
