### ISSUE TITLE
ggtags-navigation-mode does not allow to rebind keys with a hook

### ISSUE THREAD

**Issue by bartpolot** [leoliu/ggtags#115]
In navigation mode, I find the `M-n` and `M-p` default behaviour annoying due to lack of context in the code, as results are most often at the bottom or the top of the buffer. I tried to rebind the keys with a hook, but it doesn't seem to work. Here is my relevant code:

```elisp
(defun next-item-and-center ()
  "Next item and center"
  (interactive)
  (next-error)
  (recenter))
(defun prev-item-and-center ()
  "Prev item and center"
  (interactive)
  (previous-error)
  (recenter))

(defun my-gg-hook ()
  (define-key ggtags-navigation-mode-map (kbd "M-n") 'next-item-and-center)
  (define-key ggtags-navigation-mode-map (kbd "M-p") 'prev-item-and-center))
(add-hook 'ggtags-navigation-mode-hook 'my-gg-hook)
```

it works if redefined manually after entering the mode, so my guess is the hook that's failing.

For the moment I use a `M-N` and `M-P` workaround.

**Comment by bartpolot** [comment]
After a look at the code I see that the keymap's name is `ggtags-navigation-map` instead of the expected `ggtags-navigation-mode-map`. The following code does work:

``` elisp
(defun my-gg-hook ()
  (define-key ggtags-navigation-map (kbd "M-n") 'next-item-and-center)
  (define-key ggtags-navigation-map (kbd "M-p") 'prev-item-and-center))
(add-hook 'ggtags-navigation-mode-hook 'my-gg-hook)
```

**Comment by leoliu** [comment]
Hi @bartpolot,

See also `ggtags-find-tag-hook` which suits well for your use case.

Leo
