### ISSUE TITLE
Cannot find global excecutable on windows

### ISSUE THREAD

**Issue by shanavas786** [leoliu/ggtags#119]
I am trying to use global with emacs in windows. 
I use this in my .emacs
(require 'ggtags )
(setq ggtags-program-path "path-to-global-bin")

But when I execute any ggtags command I am getting error "Searching for program: no such file or directory, global"

temporarily fixed by adding global-bin path to environment variable. Its better to make the path configurable

**Comment by leoliu** [comment]
Hi @shanavas786,

You need to set `ggtags-executable-directory`. There is no `ggtags-program-path`.

HTH,
Leo

**Comment by shanavas786** [comment]
Got it. Thanks

**Comment by hendrikweisser** [comment]
I just had this same problem on a Mac, where I installed Global locally via Homebrew. Would it make sense to consider Emacs' "exec-path" variable when looking for the "global" executable? (So additional paths would only have to be specified in one place.)

**Comment by leoliu** [comment]
Hi @hendrikweisser,

Emacs on mac may have some quirks. i.e. not picking up the PATH envvar. So this is a mac emacs problem. There is little ggtags can do in this case.

Leo

**Comment by tuhdo** [comment]
There's already a package to solve that problem: https://github.com/purcell/exec-path-from-shell

**Comment by leoliu** [comment]
Indeed, it is not difficult to solve. I normally just use one that doesn't have that problem. Macport emacs has served me well for 8 years.

**Comment by hendrikweisser** [comment]
@tuhdo: Thanks for the suggestion (and for your C/C++ IDE tutorial!). It looks to me like that package would set the "exec-path" variable for me, but ggtags doesn't check "exec-path" when looking for "global".

@leoliu: Thanks for the quick reply.
> There is little ggtags can do in this case.

Well, it could consider "exec-path", which I think would be the right thing to do (see https://www.emacswiki.org/emacs/ExecPath).

**Comment by leoliu** [comment]
hi @hendrikweisser,

`ggtags` doesn't do anything special; it mostly just calls `process-file`. So if emacs is messed up anything depends on `process-file` is too.

Leo
