### ISSUE TITLE
ggtags can not find definition

### ISSUE THREAD

**Issue by ailisp** [leoliu/ggtags#122]
I encounter a strange problem, when call `ggtags-show-definition` at any place will show `[definition not found]` and when call `ggtags-update-tags` will show this in message:
```
ggtags-make-project: (error "`global' non-zero exit: global: both of -s and -r are not allowed.")
`global -u' in progress...done (0.94s)
ggtags-make-project: (error "`global' non-zero exit: global: both of -s and -r are not allowed.")
```
But if I use ggtags to generate HTML files, it just work perfectly. How to solve this problem?
Happy new Year :-)

**Comment by leoliu** [comment]
Hi @ailisp,

Happy new year!

It sounds like you are using an older version of GNU global. What is the output of `global --version`?

Thanks,
Leo

**Comment by ailisp** [comment]
Thank you, you are right, global version is 5.7.1, it is a version in 2008, I try the new 6.5 version and it works perfectly.

**Comment by leoliu** [comment]
Excellent.
