### ISSUE TITLE
Help using ggtags with prebuild gtags Database

### ISSUE THREAD

**Issue by njdan5691** [leoliu/ggtags#127]
GTAGSROOT=/inc/inc34.1/inc34.124
GTAGSDBPATH=/inc/inc34.1/inc34.124/xref/gtags

I build my gtags database for the read only directory GTAGSROOT in GTAGSDBPATH but when I try
to use ggtags it always ask me for the root directory, so it can try and build the tags databases, is there a way to get ggtags to just use what is built already? I did a little googling and it seems that the solution might residing in the gtags.conf file but for the life of my I can figure what variables to set in there.

Any help would be very much appropriated .

I should add that just using `global` on the command like works as expected.

**Comment by leoliu** [comment]
Try eval`(ggtags-process-string "global" "-pr")` in emacs to see if it returns the GTAGSROOT that you have set up.

**Comment by njdan5691** [comment]
yes it does

**Comment by leoliu** [comment]
What does eval `(ggtags-find-project)` in a buffer visiting a file from the project return?

**Comment by njdan5691** [comment]
nil

**Comment by leoliu** [comment]
hi @njdan5691, could you confirm the fix? Thanks.

**Comment by njdan5691** [comment]
It does not ask for the Root directory any more but I get `Wrong type argument: sequencep, 1` when
trying to M-. on  a symbol. I just loaded the new version of ggtags.el from with in emacs with load-file. Is there something else I need to do?

**Comment by leoliu** [comment]
Maybe start a new emacs, or `toggle-debug-on-error` to get and paste the backtrace here?

**Comment by njdan5691** [comment]
```
Debugger entered--Lisp error: (wrong-type-argument sequencep 1)                                     
  mapcar(substitute-env-vars 1)
  (let ((process-environment (copy-sequence process-environment))) (and -gtagsroot- (setenv "GTAGSR$
  (append (let ((process-environment (copy-sequence process-environment))) (and -gtagsroot- (setenv$
  (let* ((-ggtags-project-root- ggtags-project-root) (-gtagsroot- (if (ggtags-find-project) (progn $
  (progn (let* ((-ggtags-project-root- ggtags-project-root) (-gtagsroot- (if (ggtags-find-project) $
  (unwind-protect (progn (let* ((-ggtags-project-root- ggtags-project-root) (-gtagsroot- (if (ggtag$
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (let* ((-ggtags-project-root$
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer$
  (progn (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp$
  (if (ggtags-find-project) (progn (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-curre$
  ggtags-project-file-p("/home/dan/inc/inc34.1/cnc/cpymem/src/cpymem_fuj.c")
  (not (ggtags-project-file-p buffer-file-name))
  (or (eq what (quote definition)) (not buffer-file-name) (not (let ((cl-x (ggtags-find-project))) $
  (cond ((eq what (quote include)) (ggtags-find-file name)) ((or (eq what (quote definition)) (not $
  ggtags-find-tag-dwim("strpar" nil)
  funcall-interactively(ggtags-find-tag-dwim "strpar" nil)
  call-interactively(ggtags-find-tag-dwim nil nil)
  command-execute(ggtags-find-tag-dwim)
```

**Comment by njdan5691** [comment]
If it makes a difference i believe my database files are sqlite

**Comment by leoliu** [comment]
hi @njdan5691, something in your `process-environment` is causing the error? could you post the value of `process-environment`?

**Comment by njdan5691** [comment]
That was it. It was set to 1 because I was trying random stuff, mostly because my elisp kung-fu
is weak. Thanks so much for your help.

**Comment by leoliu** [comment]
Excellent and thanks for the report.
