### ISSUE TITLE
Hi,I want use popup-tip api to show the result,as follow modified of the source code not work.

### ISSUE THREAD

**Issue by linux-xhyang** [leoliu/ggtags#128]
(defcustom ggtags-print-definition-function
  (lambda (s) (popup-tip (format "%s" (or s "[definition not found]"))))
  "Function used by `ggtags-show-definition' to print definition."
  :type 'function
  :group 'ggtags)

**Comment by leoliu** [comment]
What doesn't work?

**Comment by linux-xhyang** [comment]
when mouse move,the ggtags-highlight-tag-at-point echo function definition with minibuffer,not show with popup-tip

**Comment by leoliu** [comment]
Try the following instead:

```
(setq ggtags-print-definition-function
      (lambda (s) (popup-tip (format "%s" (or s "[definition not found]")))))
```
