### ISSUE TITLE
Jumping to variables references in different library added through GTAGSLIBPATH

### ISSUE THREAD

**Issue by dhiraj113** [leoliu/ggtags#129]
I am curious to know if it is possible to use ggtags to jump to all variable references in the directories included by GTAGSLIBPATH. Currently, I am able to jump to some references using M - ] but not all.

There is a bit of discussion regarding this at https://tuhdo.github.io/c-ide.html under the section.
**Using generated database from GNU Global**. 

The author their quotes the following 

> However, remember that you can only jump to tag definitions of external dependencies, and nothing else (such as files or references). 

Is that the case? Is there no way to freely jump across all references in GTAGSLIBPATH just as if they were present in the current directory.

**Comment by leoliu** [comment]
`M-]` goes a bit further i.e. if it cannot find any references in current project it will continue search in `GTAGSLIBPATH`. ggtags is just a frontend to gnu `global` and ideally it should depend solely on `global` to do the heavy lifting. It diverges at times when it is not too much trouble but I think it should do that as little as possible.

**Comment by dhiraj113** [comment]
I get what you are saying but that's not exactly what I am looking for. I will try to re-phrase my question. Suppose, I have two source directories `A` and `B` with the source code in directory `B` dependent (having references) on the source code in directory `A`. What I am looking for is a way to quickly browse the code back-n-forth in the directories `A` and `B`. I have tried the following two methods:

**Method-1**
Run gtags command in directories `B` and `A`. Open emacs with ggtags from directory `B` and set the path of directory `A` to GTAGSLIBPATH environment variable from within emacs. This works for a few references using `M-]` but misses most of them. Moreover, `M-`. doesn't list the references in directory `A`.

**Method-2**
Manually copy both `B` and `A` into a new top level directory `T` and run gtags command in `T`. Using emacs with ggtags from `T` does what I am looking for.  Is there a way achieve this same functionality by just setting the GTAGSLIBPATH (method1) without having the need to do a manual copy.

This looks logically simple, but I don't know if any extra support from GNU Global is required or it can be achieved by just modifying ggtags code.

**Comment by leoliu** [comment]
Hi @dhiraj113,

Sorry I missed your reply.

The fundamental issue is `global` doesn't search GTAGSLIBPATH for anything other than definitions. It would be tricky if not impossible to make this work without support from `global`.

BTW, for such situations I normally just sym-link `A` into `B`.

**Comment by dhiraj113** [comment]
Okay. Thanks. Symbolic would be simpler thing to do :).

Thanks for the awesome package btw 👍
