### ISSUE TITLE
Warning when compiling under 25.1

### ISSUE THREAD

**Issue by csantosb** [leoliu/ggtags#130]
Hi,

I get this when I compile ggtags

    ggtags.el:928:18:Warning: ‘find-tag-marker-ring’ is an obsolete
    variable (as of 25.1); use ‘xref-push-marker-stack’ or
    ‘xref-pop-marker-stack’ instead.

I guess some upgrade is needed to be compliant with 25.1

Thanks

**Comment by leoliu** [comment]
Should be fixed now. Thanks for the report.
