### ISSUE TITLE
sentinel error

### ISSUE THREAD

**Issue by albert748** [leoliu/ggtags#131]
after setup, find definitions always prompt error message:

Global found 1 definition
error in process sentinel: if: Wrong type argument: stringp, nil
error in process sentinel: Wrong type argument: stringp, nil

If more then one definitions found, no error would happen.

the error sentinel reported look like triggered by "ggtags-global-handle-exit"

any idea for fixing?

**Comment by leoliu** [comment]
hi @albert748 

could you provide a recipe to reproduce the bug preferably starting emacs with -q?

**Comment by albert748** [comment]
After toggle debug-on-error, looks more clear.

ggtags version: ggtags-20161001.1836
emacs: GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.20.9) of 2016-09-18
global: 6.5.5

> 
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("*compilation*" nil)
  (if (string-match "*compilation*" (buffer-name buf)) (progn (bury-buffer "*compilation*") (winner-undo) (message "NO COMPILATION ERRORS!")))
  (if (string-match "exited abnormally" str) (message "compilation errors, press C-x ` to visit") (if (string-match "*compilation*" (buffer-name buf)) (progn (bury-buffer "*compilation*") (winner-undo) (message "NO COMPILATION ERRORS!"))))
  compilation-finish-hide-buffer-on-success(#<killed buffer> "finished\n")
  run-hook-with-args(compilation-finish-hide-buffer-on-success #<killed buffer> "finished\n")
  compilation-handle-exit(exit 0 "finished\n")
  compilation-sentinel(#<process global> "finished\n")
>

**Comment by albert748** [comment]
Sorry, the defect caused by other library code, that also add sentinel hook but not checked "buf" existence (because ggtags already handle sentinel change, other handlers shall get "Killed buffer" which is null)

I'll report this bug to original author.
