### ISSUE TITLE
Support for universal-ctags

### ISSUE THREAD

**Issue by CSRaghunandan** [leoliu/ggtags#132]
Hello, 

I'm running on Mac, emacs 25.1-1. 
I install `global` and installed `universal-ctags` using `brew`. But, when I try to generate tags, `gtags` exits with an error (because I do not have `ctags` installed) and emacs is executing `gtags` command with `ctags` label.

after browsing a bit, I found out that to use `gtags` with universal tags, we need to specify `gtagslabel` as `new-ctags` and as expected, if run `gtags --gtagslabel=new-ctags` in shell, the tags are generated.  I get an error if i try to use gtags with `ctags` as label.

Even after I added `export GTAGSLABEL=new-ctags` in my `bash_profile`, emacs still tries to run gtags with `ctags` label instead of `new-ctags` label and I get this error :- 

```
gtags: execvp failed.
gtags: unexpected EOF.
```

How can I fix this problem? Is there a way to instruct ggtags-mode to always use `universal-ctags` ?

**Comment by leoliu** [comment]
If I remember correctly, `GTAGSLABEL` only choose the target in `gtags.conf`, which has something like these lines:

```
default:\
        :tc=native:tc=pygments:
native:\
        :tc=gtags:tc=htags:
user:\
        :tc=user-custom:tc=htags:
ctags:\
        :tc=exuberant-ctags:tc=htags:
pygments:\
        :tc=pygments-parser:tc=htags:
.......
```

If I am not mistaken the ctags executable is specified at compile time, so no amount of setting `GTAGSLABEL` will help.

You might want to raise this issue on global's mailing list so that it can work better with `universal-ctags`.

**Comment by CSRaghunandan** [comment]
I was going through [this reddit](https://www.reddit.com/r/emacs/comments/3pni17/ctags_etags_or_gtags/) thread and people have mentioned they got it to work with `universal-ctags`. I was thinking, I did something wrong with my setup that messed things up. I followed the exact steps mentioned in that thread, but to no avail :(

**Comment by leoliu** [comment]
I guess you need to compile `global` and point to the `universal-ctags` executable something like this:

```
./configure --prefix=${global_install_dir} --with-exuberant-ctags=${my_ctags_bin_location}
```

**Comment by CSRaghunandan** [comment]
I compiled global like so :- 
`./configure --with-exuberant-ctags=/usr/local/bin/ctags` 
`/usr/local/bin/ctags` points to the `ctags` executable. It did not work. 

Do I have to remove and compile it again like you mentioned above ?

**Comment by leoliu** [comment]
Looks like you compiled it correctly. Try this to see if it global works without using the `ggtags` frontend.

1. copy `$HOME/.globalrc` to your project as file `gtags.conf`
2. change `gtags.conf`
```
default:\
        :tc=native:
```
to
```
default:\
        :tc=ctags:
```
3. run `gtags` in terminal

Does it work?

**Comment by CSRaghunandan** [comment]
Hmm setting default to `:tc=ctags: doesn't seem to work for universal-ctags. Instead I changed default to `:tc-new-ctags:` and it seems to work. 

BUT, there is one big problem. Even if i make a slight modification for the files and save it, the tags stop working. I see no definitions in it.
I've to delete the tags and regenerate them again. This is not how it's supposed to work I guess? Whats going on?

**Comment by CSRaghunandan** [comment]
Okay, this is strange. I first tested it out with a simple `rust` program. 
Now I tested it again with `python` and I can generate them tags fine, but after making modifications and saving file, the tags don't disappear like for `rust-mode`. But, they are stale tags and do not get updated to the newer modified file. I have to do either of these two things :- 
1. update tags and kill and reopen buffer.
2. remove tags and generate tags all over again.

Ahh. I'm not sure what's going on here. I did use `ggtags` before and it automatically updated tags after i saved the file. now its broken with `universal-ctags`

**Comment by leoliu** [comment]
That's indeed odd. I suggest report to gnu global mailing list where people would have better idea.

**Comment by Schievel1** [comment]
If someone stumbles upon this problem:
GNU Global needs to be compiled with `./configure  --with-universal-ctags=/usr/local/bin/ctags` or whereever your universal-ctags binary is. For example, the universal-ctags binary for Gentoo is `/usr/bin/exuberant-ctags` [sic] from the package `dev-util/ctags` (which gets it's source from https://github.com/universal-ctags/ctags, yes it is really confusing). 
ggtags is using the gtagslabel `ctags`. You can simulate it's behavior with the command `gtags --gtagslabel=ctags` 
You can use the environment variable `GTAGSLABEL` to change this and get this environment variable in emacs somehow. (Some emacsen create their own environment once and then load in from a file. So check if it's really set with `M-x getenv`.)
There is this in `/etc/gtags.conf`
```
new-ctags:\
	:tc=universal-ctags:tc=htags:
```
and running `gtags --gtagslabel=new-ctags` works indeed. So setting GTAGSLABEL=new-ctags should work. 

Or, to make it use universal-ctags permanently, you can change the lines in `/etc/gtags.conf` from 
```
ctags:\
	:tc=exuberant-ctags:tc=htags:
```
to 
```
ctags:\
	:tc=universal-ctags:tc=htags:
```
