### ISSUE TITLE
ggtags-find-tag-dwim throws error - "`global' non-zero exit: global: GTAGS not found."

### ISSUE THREAD

**Issue by madhavan020985** [leoliu/ggtags#135]
When somebody opens a new project in emacs, and try to use `goto-definition`, it fails with the error, `GTAGS not found`. When i investigated into it, i see that, `ggtags-find-tag-dwim` func try to see if there is already a ggtags-project existing and if not, create tags. 
Function `ggtags-find-project` tries to run the command `global -pr` inside which throws an error, if it doesn't find `GTAGS` file. I see, you have put a comment referring an issue, `https://github.com/leoliu/ggtags/issues/22, 

I fixed it locally by wrapping the call to ggtags-process-string inside a condition-case statement as,

```
(condition-case nil
   (ggtags-process-string "global" "-pr")
 (error nil))
```

I had to add the fix in the function `ggtags-make-project` too.

**Comment by leoliu** [comment]
Should be fixed now. Thanks for the report.
