### ISSUE TITLE
ggtags-show-definition

### ISSUE THREAD

**Issue by yanglimingchn** [leoliu/ggtags#136]
can you add a switch for auto ggtags-show-definition at point in minibuffer, because in tramp mode it is always connect to remote server, and will slow down normal work.
I am not good at elisp, I comment these code below
        ;; Work around http://debbugs.gnu.org/19324
        ;; (or eldoc-documentation-function
        ;;     (setq-local eldoc-documentation-function #'ignore))
        ;; (add-function :after-until (local 'eldoc-documentation-function)
        ;;               #'ggtags-eldoc-function '((name . ggtags-eldoc-function)
        ;;                                         (depth . -100)))

**Comment by leoliu** [comment]
Maybe try something like this:

```
(add-hook 'ggtags-mode-hook (lambda () (setq-local eldoc-documentation-function #'ignore)))
```

**Comment by yanglimingchn** [comment]
thanks
