### ISSUE TITLE
file-error "Searching for program" "No such file or directory" "global"

### ISSUE THREAD

**Issue by Rookie-iOS** [leoliu/ggtags#137]
M-x: ggtags-mode show this:
Error running timer ‘ggtags-highlight-tag-at-point’: (file-error "Searching for program" "No such file or directory" "global")

M-x : shell  cd root directory than which global hint gtags not find
M-x : getenv PATH include the global path

the emacs version is 25.1

**Comment by leoliu** [comment]
It is an old bug of emacs on OS X. Maybe report to emacs and see if they can get it fixed after all it's been years.

**Comment by Rookie-iOS** [comment]
@leoliu if i want to use ggtags, how can i avoid this bug? thanks!

**Comment by leoliu** [comment]
See if this is of any help https://github.com/purcell/exec-path-from-shell

**Comment by Rookie-iOS** [comment]
thanks!
