### ISSUE TITLE
compilation-filter error

### ISSUE THREAD

**Issue by yanglimingchn** [leoliu/ggtags#138]
when I use 'M-.' to find tag, I usual got error, backtrace show below
Debugger entered--Lisp error: (error "Marker points into wrong buffer" #<marker (moves after insertion) in no buffer>)
  #[0 "\300b\210\301\302}\210\300\303\211\223\210\301\303\211\223\210\302\303\211\223\207" [#<marker (moves after insertion) in no buffer> #<marker in no buffer> #<marker (moves after insertion) in no buffer> nil] 3]()
  compilation-filter(#<process global> "redis/src/aof.c:455:void [01;31mfeedAppendOnlyFile[m(struct redisCommand _cmd, int dictid, robj *_argv, int argc) {\n1 object located (using '/home/Source/redis/GTAGS').\n")

Emacs Message buffer show:
error in process filter: compilation-filter: Marker points into wrong buffer: #<marker (moves after insertion) in no buffer>
error in process filter: Marker points into wrong buffer: #<marker (moves after insertion) in no buffer>

**Comment by leoliu** [comment]
How do you get this error?

**Comment by yanglimingchn** [comment]
I  switch 'toggle-debug-on-error' on, got the error, I use ggtags in tramp mode
Emacs version: GNU Emacs 25.1.1 (x86_64-unknown-cygwin) of 2016-09-18
ggtags version is git master

**Comment by leoliu** [comment]
Unfortunately I cannot reproduce it here.
