### ISSUE TITLE
Exuberant Ctags not found.

### ISSUE THREAD

**Issue by dineshadepu** [leoliu/ggtags#144]
Hi, 
I am trying to create ggtags. First, when try to call header files, it checks if there are any gtags created, if there are no such files, it asked for "root directory". 

Then it asks if I need any "Ctags". If I say yes then I get the following error.
```
‘gtags’ non-zero exit: gtags: Exuberant Ctags not found. Please see ./configure --help.
```
By ignoring this message, I tried to look at the definition then I got this error
```
ggtags-make-project: (error "‘global’ non-zero exit: global: /Users/harishraja/clanguage/GRTAGS seems corrupted.")
```
Detailed compile traceback is
```
global -v --result=path --color=always --path-style=shorter --path -- "myMath.h"
global: GPATH not found.
```
But If i ignore using Ctags it works perfectly. 

How can I make it work with Ctags?

**Comment by leoliu** [comment]
See https://github.com/leoliu/ggtags#install-global-and-plugins
