### ISSUE TITLE
CUDA (.cu, .cuh) file support

### ISSUE THREAD

**Issue by helinwang** [leoliu/ggtags#147]
Hi,

Are there any support for cuda? I tried to edit my `~/.ctags` file and add:
```text
--langmap=c++:+.cu.cuh
```
But it does not seem to be working.

**Comment by helinwang** [comment]
Seems to be working after replacing Exuberant Ctags with https://github.com/universal-ctags/ctags/issues/1220

**Comment by leoliu** [comment]
`ggtags-mode` doesn't do highlight. the highlight should come from whatever major mode you use with .cu files. may be try `M-x c-mode`.

**Comment by helinwang** [comment]
Thanks!
