### ISSUE TITLE
How to add assembly function defines to ggtags?

### ISSUE THREAD

**Issue by hisnawi** [leoliu/ggtags#149]
Before using ggtags I used to generate TAGS file with:

`     find . -type f -iname \"*.[chSs]\" | etags --regex='{asm}/[\t]*ENTRY_FUNC[ \t]*\([^ ]*\)/' -")`

Since some of our projects C function calls are defined in assembly with the Macro (ENTRY_FUNC()).
Unfortunately, ggtags don't recognize as these are tags for these functions. How to include these Macros as possible tags with ggtags package?

**Comment by leoliu** [comment]
`ggtags` is using gnu global to index source files. So this has to be asked on gnu global mailing list. I don't have an answer ready though.

**Comment by hisnawi** [comment]
Sure, assuming I found the right option for global, how to have ggtags add that option to the command when running gtags? Does ggtags reference some .ctags file at the project's root directory that have the extra options?

**Comment by leoliu** [comment]
No unless `global` does that already. So if you set up global by placing a `gtags.conf` file at your project root. `ggtags` will just work.

**Comment by hisnawi** [comment]
My understanding is that ggtags use gtags to create the TAGS, and global to navigate them. gtags has an option for --regexp. My question is how to pass that to ggtags when creating the TAGS? Through a file in the root dir? through ggtags variable?
