### ISSUE TITLE
ggtags + eldoc not working

### ISSUE THREAD

**Issue by hisnawi** [leoliu/ggtags#150]
This is my setup:
```
      (use-package eldoc
        :defer t
        :diminish eldoc-mode
        :init (add-hook 'prog-mode-hook #'eldoc-mode)
       )

      (use-package irony-eldoc
        :ensure t
        :disabled
        :defer t
        :init
        (with-eval-after-load 'irony
          (add-hook 'irony-mode-hook #'irony-eldoc))
        )

  (use-package ggtags
    :ensure t
    :config 
    (add-hook 'c-mode-common-hook
              (lambda ()
                (when (derived-mode-p 'c-mode 'c++-mode 'java-mode 'asm-mode)
                  (ggtags-mode 1)
                  (setq-local eldoc-documentation-function #'ggtags-eldoc-function)
                  )))
    (setq ggtags-mode-line-project-name nil)
    (define-key ggtags-mode-map (kbd "C-c g s") 'ggtags-find-other-symbol)
    (define-key ggtags-mode-map (kbd "C-c g h") 'ggtags-view-tag-history)
    (define-key ggtags-mode-map (kbd "C-c g r") 'ggtags-find-reference)
    (define-key ggtags-mode-map (kbd "C-c g f") 'ggtags-find-file)
    (define-key ggtags-mode-map (kbd "C-c g c") 'ggtags-create-tags)
    (define-key ggtags-mode-map (kbd "C-c g u") 'ggtags-update-tags)
    (define-key ggtags-mode-map (kbd "M-,")     'pop-tag-mark)
)
```

But nothing shows up in the mini buffer when the cursor on top of functions/defines...etc

**Comment by leoliu** [comment]
It's working here. So this might be an issue of your setup. Move point to a function/tag and eval `(ggtags-eldoc-function)` does it print any thing?

For emacs >= 24.4 eldoc support is automatically enabled so `(setq-local eldoc-documentation-function #'ggtags-eldoc-function)` is not needed.

**Comment by hisnawi** [comment]
This is what I see:

eval-expression: Symbol's value as variable is void: ggtags-eldoc-function

**Comment by hisnawi** [comment]
I removed everything from my init.el file except this:

```
  (use-package ggtags
    :ensure t
    :config 
    (add-hook 'c-mode-common-hook
              (lambda ()
                (when (derived-mode-p 'c-mode 'c++-mode 'java-mode 'asm-mode)
                  (ggtags-mode 1)
                  )))
    )

```
enabled eldoc-mode, but I still don't see anything in the mini buffer show up. Although ggtags works fine, I can jump between tags with M-. and M-,

evaluating ggtags-eldoc-function when on a define gives this:

```
Debugger entered--Lisp error: (void-variable ggtags-eldoc-function)
  eval(ggtags-eldoc-function nil)
  eval-expression(ggtags-eldoc-function nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)


```

**Comment by leoliu** [comment]
Do something like this: `M-: (ggtags-eldoc-function) RET`

**Comment by hisnawi** [comment]
My bad. It returns nil.

**Comment by leoliu** [comment]
1. Eval `(ggtags-eldoc-function)`
2. Wait a few seconds but don't move point
3. `(ggtags-eldoc-function)`

Does step 3 return anything?

**Comment by leoliu** [comment]
The key to get eldoc working is to get `ggtags-show-definition` working. So you can just move point to a function/tag and press `M-?` (which is bound to `ggtags-show-definition` in ggtags-mode).

**Comment by hisnawi** [comment]
Eval: (ggtags-eldoc-function) keeps returning nil.

ggtags-show-definition says: [definition not found] although M-. on the definition works and takes me to the tag.

**Comment by hisnawi** [comment]
Ok worked. I was using an older globals version. Updated to the latest 6.5.7 and now it worked. Thanks.
