### ISSUE TITLE
Can't find references to functions/definitions 

### ISSUE THREAD

**Issue by hisnawi** [leoliu/ggtags#151]
I am not able to show references to a function/definition using M-] key.

I have this .ctag setup:

--extras=+r
--fields=+r

I use gtags with universal-ctags to generate the tags files.

gtags --gtagslabel=new-ctags
ctags: Warning: --extra option is obsolete; use --extras instead

But I can't find references.

This is what ggtags show in emacs:
Global found 0 references

If I use the regular gtags to generate TAG files then I can' find the references no problem.

Am I missing something from the config file (.ctag)?

**Comment by leoliu** [comment]
ctags can not generate references. you need to combine it with the pygments plugin.

**Comment by hisnawi** [comment]
Great, Thanks for your answer. Could you please tell me how to do that? Or point me to a link?
Is it done through the .ctag file? The gtags.conf file?

**Comment by leoliu** [comment]
Maybe check out https://github.com/leoliu/ggtags#install-global-and-plugins and follow the pointers.

**Comment by Apteryks** [comment]
Hi,

I got confused at this too, thought there was an issue with ggtags not finding references.  Perhaps the README.rst should mention that in order for the `find-reference` features to work, a reference tags supporting backend such as pygments must be used, e.g. by setting the `GTAGSLABEL` environment variable to `pygments`?

**Comment by Apteryks** [comment]
Also, the default behavior (unless `GTAGSLABEL` is set) is to prompt for `"Use `ctags' backend? "`, which won't create reference tags.  Perhaps leaving this to the default native backend would be a better idea?  It supports reference tags and seems faster than ctags, on my machine:

```
~/src/rpm [env]$ rm -rf GPATH GRTAGS GTAGS && time GTAGSLABEL=ctags gtags

real    0m0.415s
user    0m0.344s
sys     0m0.071s

~/src/rpm [env]$ rm -rf GPATH GRTAGS GTAGS && time GTAGSLABEL=default gtags

real    0m0.205s
user    0m0.134s
sys     0m0.046s
```
