### ISSUE TITLE
Creating tags, keeps asking for project root

### ISSUE THREAD

**Issue by hisnawi** [leoliu/ggtags#153]
I have projectile installed and gtags.conf file in the project root. Still when creating ggtags tags it keep asking for the location of the root dir. Did I miss a setting?
```
  (use-package ggtags
    :ensure t
    :config 
    (unbind-key "M-<" ggtags-mode-map)
    (unbind-key "M->" ggtags-mode-map)
    (add-hook 'c-mode-common-hook
              (lambda ()
		(when (derived-mode-p 'c-mode 'c++-mode 'java-mode 'asm-mode)
                  (ggtags-mode 1)
                  )))
    (add-hook 'asm-mode-hook #'ggtags-mode)
    (setq ggtags-mode-line-project-name nil)
    (define-key ggtags-mode-map (kbd "C-c g s") 'ggtags-find-other-symbol)
    (define-key ggtags-mode-map (kbd "C-c g h") 'ggtags-view-tag-history)
    (define-key ggtags-mode-map (kbd "C-c g r") 'ggtags-find-reference)
    (define-key ggtags-mode-map (kbd "C-c g f") 'ggtags-find-file)
    (define-key ggtags-mode-map (kbd "C-c g c") 'ggtags-create-tags)
    (define-key ggtags-mode-map (kbd "C-c g u") 'ggtags-update-tags)
    (define-key ggtags-mode-map (kbd "C-c g t") 'ggtags-find-definition)
    (define-key ggtags-mode-map (kbd "M-?")     'ggtags-show-definition)
    (define-key ggtags-mode-map (kbd "M-,")     'pop-tag-mark)

    ;; When ggtags fail try regular find-tag
    (defadvice ggtags-global-exit-message-function
	(around try-etags-on-failure activate compile)
      "On failure to find any item, try normal find-tag'.
       This is to locate global variable definitions."
      (let ((status ad-do-it))
	(when (equal status '("found 0 definitions" . 0))
          (message "Trying find-tag' on %s" ggtags-current-tag-name)
          (xref-find-definitions ggtags-current-tag-name)) status))
    )

```

**Comment by leoliu** [comment]
It only ask the root once per project. root directory is defined by what `global -pr` returns. so placing `gtags.conf` in a directory doesn't automatically make that directory project root.

**Comment by hisnawi** [comment]
It actually keeps asking for root project every time I specifically do:
ggtags-create-tags

Notice I am not doing an update but a full blown create.

Is it possible to get a variable that we can set?
I think setting it to projectile-root will solve this issue.

**Comment by leoliu** [comment]
"It actually keeps asking for root project"

Something is not working properly. It could be a combination of things. If you can provide a recipe to reproduce the problem (preferably with `emacs -q`) I will find time to find the root cause.

there is an internal variable `ggtags-project-root` but you should use it as the last resort.

**Comment by hisnawi** [comment]
Apologies for the noob question, but using (emacs -q) wont load ggtags package.
Is there a way to start emacs with only ggtags package without removing 99% of my init.el file?

**Comment by leoliu** [comment]
yes. normally `emacs -q` starts without user's init file and only load things from `site-start.el`. So after starting `emacs -q` you can load `ggtags` with `M-x load-file`.

**Comment by hisnawi** [comment]
I tried it with (emacs -q) and loading only ggtags.el file. It still ask me for the root directory every time I execute ggtags-create-tags

**Comment by leoliu** [comment]
`ggtags-create-tags` always ask for a root directory. Users normally don't need to use `ggtags-create-tags` unless they want to make a subdirectory a project root i.e. If you /projects/a is a project root and you need a sub-project in `/projects/a/src`.

**Comment by hisnawi** [comment]
Got it. Thanks.

**Comment by hisnawi** [comment]
One more question. Is there a way to find the full command ggtags ran when doing ggtags-create-tags?
I want the full command that also picks options in .ctags file.

**Comment by leoliu** [comment]
No, there is no direct way. Options used are controlled a few variables. But you can guess what options are used by looking at the implementation of `ggtags-create-tags`.
