### ISSUE TITLE
Cygwin/Msys2 "global" returns unusable project root in ggtags-find-project

### ISSUE THREAD

**Issue by garyo** [leoliu/ggtags#154]
On Windows, with cygwin or msys2 "global", `global -pr` returns `/c/my/dir`. With native emacs, this dir doesn't exist. It would be great if `ggtags-find-project` would use `cygpath -m` if it exists to postprocess that path (which would become `c:/my/dir` in that case).

**Comment by leoliu** [comment]
Hi @garyo,

Sorry for the trouble on Windows. Could you take a look at issue #123 and #121 and see if there is a solution for you? Thanks.

Leo
