### ISSUE TITLE
ggtags-fontify-code improvement suggestion

### ISSUE THREAD

**Issue by kaushalmodi** [leoliu/ggtags#158]
Hello,

As a followup to the upstream fix for https://github.com/leoliu/ggtags/issues/157, a discussion spawned off on the [emacs-devel thread][1] where Stefan Monnier @monnier suggested this:

> Looking at ggtags.el, I also wonder why the buffer survives the call to
ggtags-fontify-code.  I would have expected ggtags-fontify-code to look
more like:

```el
(cl-defun ggtags-fontify-code (code &optional (mode major-mode))
  (cl-check-type mode function)
  (cl-typecase code        ;; FIXME: Using `stringp` is more efficient.
    ((not string) code)
    (string
     (with-temp-buffer
       (insert code)
       ;; FIXME: `delay-mode-hooks' needs a comment
       (delay-mode-hooks (funcall mode))
       (font-lock-ensure)
       (buffer-string)))))
```

[1]: http://lists.gnu.org/archive/html/emacs-devel/2017-09/msg00618.html

**Comment by leoliu** [comment]
Thanks for posting this here. The `delay-mode-hooks` was added recently:
```
    Remove delay-mode-hooks from ggtags-fontify-code
    
    which may interact badly with jit-lock-after-change causing eldoc to
    throw errors such as: eldoc error: (args-out-of-range 1 36).
```

but I forgot the details.

**Comment by kaushalmodi** [comment]
Even without `delay-mode-hooks`, we can do without a `" *Code-Fontify*"` buffer, by using `with-temp-buffer` instead, right?

**Comment by leoliu** [comment]
After releasing `0.8.13`, we'll require emacs 25+ and use this version instead.
