### ISSUE TITLE
add xref back end

### ISSUE THREAD

**Issue by tromey** [leoliu/ggtags#160]
Newer version of Emacs bind `M-.` and friends to `xref-*` functions (see `xref.el`) rather than to etags functions directly.  `xref` allows multiple back ends, so I think it would be good for ggtags to be another xref back end; without rebinding the various keys.

**Comment by leoliu** [comment]
This may take some time but will look into it. Thanks.

**Comment by dzop** [comment]
@leoliu If there hasn't been much progress on this issue, I have an [xref backend](https://github.com/dzop/ggtags/tree/xref) that has been working well for me if you are open to a pull request.

**Comment by leoliu** [comment]
@dzop Yes and thanks in advance.
