### ISSUE TITLE
Add a variable to pass custom arguments when running gtags

### ISSUE THREAD

**Issue by jgkamat** [leoliu/ggtags#162]
Hi!

I have a few projects where I would like to pass `--accept-dotfiles` to gtags, since some code is in hidden directories. Could we have a variable to pass `--accept-dotfiles` or have a variable to pass custom flags to gtags?

Thanks for creating this, it's made creating and using tags so easy! :smile: 

https://github.com/leoliu/ggtags/blob/master/ggtags.el#L740-L745

**Comment by leoliu** [comment]
Thanks for the suggestion. Let me know if the commit fixes the issue.

**Comment by jgkamat** [comment]
Thanks for the quick response! 

This new variable is exactly what I was looking for, thanks! :smile:
