### ISSUE TITLE
how to get ggtags to use the =file_name  with the "nearness" option of 'global'

### ISSUE THREAD

**Issue by gthaker** [leoliu/ggtags#163]
I mistakenly thought my issue was w/ 'global', but it has been pointed out to me that how ggtags uses ' global's nearness option may be the issue. Please see below:

Hello,
You need to add '=b.c' to the --nearness option.
The --from-here option has nothing to do with it.

$ global --result=grep --nearness=b.c --from-here=9:b.c foo
b.c:1:static int  foo() {
a.c:1:static int  foo() {

Regards
Shigio

=== Original post of mine =============
I have two files in a single directory, a.c and b.c each with a function "foo". If in emacs I am looking at file b.c and search for tag "foo", it goes to the definition of "foo" in file a.c. This is not what I believe is expected given from man mage:

"    [0] If the start is a file, output of local search in the file."

And indeed, this is confirmed by:

$ global -v --result=grep --color=always --nearness --path-style=shorter --from-here=9:b.c foo
a.c:1:static int  foo() {
b.c:1:static int  foo() {
2 objects located (using '/home/gthaker/ggtags-testing/GTAGS').

I expected that from b.c it would find definition in file b.c above the one in a.c (but in lexical sorting a.c comes before b.c so it is going there.)

files are as below:

:::::::::::::
a.c
::::::::::::::
static int  foo() {
  return 3;
}

main() {
  int x;

  x = foo();
}
::::::::::::::
b.c
::::::::::::::
static int  foo() {
  return 3;
}

main() {
  int x;

  x = foo();
}

**Comment by leoliu** [comment]
Thanks for the report. I just pushed a fix. Could you check it is working? Thanks.

**Comment by arichiardi** [comment]
@leoliu I don't know if this is the right place but I have a similar use case with the Clojure language. I can contribute a fix, just want to see if I am on the right page first.

In my case, search patterns can be complex strings: 

```
(foo/bar param1 param2)
```

The point can be anywhere on `foo/bar`.

In Clojure `foo` would map to a file called `foo.clj` and the search should run on `bar`. I was initially thinking that I could create a wrapper that does the split, then I have run into this issue.

I still need to pre-parse things, but is there then a way to call `global` with a custom `nearness` option as the above?

**Comment by leoliu** [comment]
hi @arichiardi,

sorry, I seem to miss this notification. In your example is `foo` like a namespace? It is a pity `global` cannot handle namespaces and probably never will be. So we may need to make use of something like `nearness`.

Your plan looks feasible.

At the moment the power of `nearness` is not fully exposed i.e. we use `--nearness=.` (per `ggtags-global-build-command`). So this has to change first. Parsing tags can be handled by customising `ggtags-bounds-of-tag-function`.

Leo

**Comment by arichiardi** [comment]
Ok @leoliu thanks for confirming! Yes `foo` is a namespace. I will try to come up with something and questions if any (likely many :smile:)

**Comment by gthaker** [comment]
Leo,

It has taken me more than a year to test this. But I am afraid the issue does not seem to be fixed.

I am using ggtags 0.8.13 w/ emacs 24.5.1  and GNU global 6.6.3

From file b.c   , my point is on line 
x = foo();

and doing a Meta-. takes me to   definition of foo in file a.c (and shows b.c as 2nd choice )  

It seems to me that it should take me to b.c  (and optionally show a.c as 2nd choice.)

![Screenshot from 2019-03-11 10:43:17](https://user-images.githubusercontent.com/12518676/54132408-8ee08d80-43ea-11e9-961d-a997a536c28c.png)

**Comment by gthaker** [comment]
when "global" is invoked by ggtags it seems we still don't supply the argument:

--from-here=9:b.c

**Comment by leoliu** [comment]
If I remember correctly `nearness` means how close matches are to the directory. If these two matches are in the same directory nearness doesn't come into play.

**Comment by gthaker** [comment]
Leo: If you consider this use case, if I am looking for function "foo" and there is one locally in this very file it seems that is the one use is interested in first!  And indeed the GNU Global folks (who had so kindly put in the NEARNESS support based on my suggestion), have shown that if  ggtags uses "--from-here=9:b.c" in invocation the desired behavior will be achieved. If nothing else can we have an option to add "from-here:..." in the invocation?

**Comment by leoliu** [comment]
Could you check why `--from-here` is missing from your example? `M-.` invokes `ggtags-find-tag-dwim` which should automatically put in the `--from-here` argument.

**Comment by gthaker** [comment]
Leo:

In ggtags.el 0.8.13 that I am using I have the below code sections. I am not an expert elisp programmer (by any means), and thus I am not sure why the "--from-here" code fragment is not used. (It must be that code just goes to "(ggtags-find-definition name)" code, never goes to the "(t ...." section that would use --from-here?



(defun ggtags-find-tag-dwim (name &optional what)
  "Find NAME by context.
If point is at a definition tag, find references, and vice versa.
If point is at a line that matches `ggtags-include-pattern', find
the include file instead.

When called interactively with a prefix arg, always find
definition tags."
  (interactive
   (let ((include (and (not current-prefix-arg) (ggtags-include-file))))
     (ggtags-ensure-project)
     (if include (list include 'include)
       (list (ggtags-read-tag 'definition current-prefix-arg)
             (and current-prefix-arg 'definition)))))
  (ggtags-check-project)    ; For `ggtags-current-project-root' below.
  (cond
   ((eq what 'include)
    (ggtags-find-file name))
   ((or (eq what 'definition)
        (not buffer-file-name)
        (not (ggtags-project-has-refs (ggtags-find-project)))
        (not (ggtags-project-file-p buffer-file-name)))
    (ggtags-find-definition name))
   (t (ggtags-find-tag
       (format "--from-here=%d:%s"
               (line-number-at-pos)
               ;; Note `ggtags-find-tag' binds `default-directory' to
               ;; project root.
               (shell-quote-argument
                (ggtags-project-relative-file buffer-file-name)))
       "--" (shell-quote-argument name)))))

(defun ggtags-find-tag-mouse (event)
  (interactive "e")
  (with-selected-window (posn-window (event-start event))
    (save-excursion
      (goto-char (posn-point (event-start event)))
      (call-interactively #'ggtags-find-tag-dwim))))

;; Another option for `M-.'.
(defun ggtags-find-definition (name)
  (interactive (list (ggtags-read-tag 'definition current-prefix-arg)))
  (ggtags-find-tag 'definition "--" (shell-quote-argument name)))

**Comment by leoliu** [comment]
Hi @gthaker,

It is not obvious what's going on. Can you prepare a sample project and show me how to reproduce the issue? Thanks.

**Comment by gthaker** [comment]
Leo,

I have attached  a zip file. Simple unzip and start emacs on file b.c.

do meta-. on call to "foo()"   in b.c, and rather than going to definition of foo in file b.c (which is nearest) for emacs loads up a.c and goes to its definition of foo. ("a.c" comes before "b.c" without --from-here)

Gautam

[issue_163.zip](https://github.com/leoliu/ggtags/files/2988133/issue_163.zip)
And this is w/ version 0.8.13 (I am on emacs 24)

**Comment by leoliu** [comment]
@gthaker, thanks, the --nearness feature wasn't tested much and there were a few bugs that I have just fixed.

BTW, your project is using the ctags backend and has no ref tags so `ggtags-find-tag-dwim` detects that and always finds definition instead.

Here is a patch against 0.8.13 in case you can't upgrade to emacs 25.

```diff
diff -u ggtags/ggtags.el ggtags/ggtags.el.orig
--- ggtags/ggtags.el.orig	2019-03-11 10:35:10.000000000 +0800
+++ ggtags/ggtags.el	2019-03-21 06:12:02.000000000 +0800
@@ -899,9 +899,11 @@
                 (default (substring-no-properties default))
                 (t (ggtags-read-tag type t prompt require-match default))))))
 
-(defun ggtags-sort-by-nearness-p ()
+(defun ggtags-sort-by-nearness-p (&optional start-location)
   (and ggtags-sort-by-nearness
-       (ggtags-process-succeed-p "global" "--nearness=." "--help")))
+       (ggtags-process-succeed-p "global" "--nearness=." "--help")
+       (concat "--nearness="
+               (or start-location buffer-file-name default-directory))))
 
 (defun ggtags-global-build-command (cmd &rest args)
   ;; CMD can be definition, reference, symbol, grep, idutils
@@ -913,7 +915,6 @@
                                (ggtags-find-project)
                                (ggtags-project-has-color (ggtags-find-project))
                                "--color=always")
-                          (and (ggtags-sort-by-nearness-p) "--nearness=.")
                           (and (ggtags-find-project)
                                (ggtags-project-has-path-style (ggtags-find-project))
                                "--path-style=shorter")
@@ -976,7 +977,11 @@
 
 (defun ggtags-find-tag (cmd &rest args)
   (ggtags-check-project)
-  (ggtags-global-start (apply #'ggtags-global-build-command cmd args)))
+  (let ((nearness (ggtags-sort-by-nearness-p
+                   (ggtags-project-relative-file
+                    (or buffer-file-name default-directory)))))
+    (ggtags-global-start
+     (apply #'ggtags-global-build-command cmd nearness args))))
 
 (defun ggtags-include-file ()
   "Calculate the include file based on `ggtags-include-pattern'."
@@ -2078,7 +2083,8 @@
   (let* ((re (cadr (assq 'grep ggtags-global-error-regexp-alist-alist)))
          (current (current-buffer))
          (buffer (get-buffer-create " *ggtags-definition*"))
-         (args (list "--result=grep" "--path-style=absolute" name))
+         (args (delq nil (list (ggtags-sort-by-nearness-p ".")
+                               "--result=grep" "--path-style=absolute" name)))
          ;; Need these bindings so that let-binding
          ;; `ggtags-print-definition-function' can work see
          ;; `ggtags-eldoc-function'.
@@ -2097,11 +2103,8 @@
                    (with-current-buffer current
                      (funcall print-fn (funcall get-fn defs)))))))
     (ggtags-with-current-project
-      (ggtags-global-output
-       buffer
-       (cons (ggtags-program-path "global")
-             (if (ggtags-sort-by-nearness-p) (cons "--nearness=." args) args))
-       show 100))))
+      (ggtags-global-output buffer (cons (ggtags-program-path "global") args)
+                            show 100))))
 
 (defvar ggtags-mode-prefix-map
   (let ((m (make-sparse-keymap)))

Diff finished.  Thu Mar 21 06:12:47 2019
```

**Comment by gthaker** [comment]
Thanks Leo:

I tested this with emacs25 and it works. (Also moved to emacs 25 as this makes most sense for me anyway).

As for ctags backend, I use ggtags a lot w/ mixed C and python code base. For C like to use gnu global's ability to have entries for references to functions, and for it to use ctags for creating python program's definition entries.  Somehow I must have misconfigured gnu global last time I build it. I will try to fix this in my env, thanks for pointing it out. It was a bit confusing as to how to configure gnu global to work properly in mixed C/Python world.

**Comment by leoliu** [comment]
@gthaker,

Excellent. Thanks for helping to get it fixed. For mixed projects ctags + pygments can work well. I used the combo on a cfengine project.
