### ISSUE TITLE
Add in instructions for using universal-ctags

### ISSUE THREAD

**Issue by jonnycyr** [leoliu/ggtags#174]
Exhuberant-ctags hasn't been maintained in a while, the maintained version is known as universal-ctags. Here's a snippet from the github page https://github.com/universal-ctags/ctags

> universal-ctags has the objective of continuing the development from what existed in the Sourceforge area. Github exuberant-ctags repository was started by Reza Jelveh and was later moved to the universal-ctags organization.

I currently have ggtags working with gnu global 6.6.2, universal-ctags, and GNU Emacs 25.3.2. I wrote up the exact steps that I did in on my .emacs.d readme https://github.com/jonnycyr/.emacs.d. 

If you'd like I can submit a pull request modifying the read me with the instructions I've created.

**Comment by leoliu** [comment]
I am glad to see there is new development in the form of universal ctags. I think we should update the README to prefer https://github.com/universal-ctags/ctags. Would you like to submit a PR? Thanks.

**Comment by jonnycyr** [comment]
Will do!
