### ISSUE TITLE
Q: counsel support?

### ISSUE THREAD

**Issue by FelipeLema** [leoliu/ggtags#175]
Would it be admisible to have counsel support?

I know that https://github.com/syohex/emacs-counsel-gtags exists, but there are two reasons I wouldn't use it.

- it seems unmaintained: I tried to contact the owner by both twitter and e-mail with no answer
- from the PRs I've done, it feels like there are several functions being re-implemented, most of them "just" because of some minor detail (namely: handling the compilation buffer is mixed with running `global` commands)

What I was thinking was to de-couple some functions to be able to extend support for different selection narrowing frameworks (compile-mode, counsel-or-ivy, helm).

I'm willing to do this, as long as the maintainers think it's something that belongs in this package. Needless to say, this work would keep `compile-mode` support _and_ add counsel support. Most likely to add unit tests to keep this promise.

**Comment by leoliu** [comment]
Hi @FelipeLema,

Sorry for the delay.

That sounds like a good idea to me. Personally I have no experience with those packages so I might not be able to offer much help beyond how to integrate with `ggtags`. Note `ggtags` is part of gnu elpa which requires copyright assignment for significant changes. I hope that is not an issue. Thanks in advance for the contribution.

Leo

**Comment by FelipeLema** [comment]
Ok. I'll create a branch+PR for working in this soon (hopefully this week).

**Comment by leoliu** [comment]
Excellent.

**Comment by FelipeLema** [comment]
While documantating the functions I realized that most of the code in this package is to get by with the default behaviour of `compilation-mode` rather than handling `global` commands.

I don't say this as a critique, but rather to make it explicit that this package's purpose is to provide an interface to `global` in emacs _through `compilation-mode`_.

As such, I'd recommend anyone arriving to this issue to head over to [my fork](https://github.com/FelipeLema/emacs-counsel-gtags) of [`emacs-counsel-tags`](https://github.com/syohex/emacs-counsel-gtags) that I'll be maintaining.

Thanks @leoliu for your good disposition.
