### ISSUE TITLE
ggtags + eldoc within tramp seems to slow down the cursor significantly

### ISSUE THREAD

**Issue by baron** [leoliu/ggtags#189]
Title pretty much explains the situation. It could be due to the project being large but the cursor constantly stutters while moving around the file. It gets much smoother when I disable eldoc in the buffer.
![2019-01-10 17 59 58](https://user-images.githubusercontent.com/2617/50957464-a346fd80-1501-11e9-805d-44313a6aa305.png)

**Comment by leoliu** [comment]
What is the value of `eldoc-idle-delay` in your setup?

Could you also try updating `ggtags-show-definition` to have a smaller CUTOFF to `ggtags-global-output` (is hardcoded as 100)?

**Comment by baron** [comment]
You are an absolute wizard! It turns out my `eldoc-idle-delay` was set to 0. 

Before
![2019-01-11 14 27 20](https://user-images.githubusercontent.com/2617/51015090-232aa180-15ae-11e9-9746-661329890b55.png)

 `eldoc-idle-delay` set to 1 and `ggtags-global-output` to 10
![2019-01-11 14 30 42](https://user-images.githubusercontent.com/2617/51015089-232aa180-15ae-11e9-9eed-b2651448c10b.png)

 `eldoc-idle-delay` set to 1 and `ggtags-global-output` to 100
![2019-01-11 14 34 27](https://user-images.githubusercontent.com/2617/51015087-22920b00-15ae-11e9-87be-afc223ed082f.png)

Thank you once again for solving another issue. Now I can use your awesome package in peace whether on tramp or local. I seriously can't work on this project without ggtags. It's a godsend.

**Comment by leoliu** [comment]
Glad to hear it.
