### ISSUE TITLE
ggtags.el:2367:11:Error: Given parent class xref-file-location is not a class

### ISSUE THREAD

**Issue by gthaker** [leoliu/ggtags#190]
I am on mint 18.3 with an uptodate system. Emacs on my install is emacs 24.5.1

I downloaded 6.6.3 and typed "make". I get error msg:

int1> make
Compiling ggtags.el

In ggtags-next-mark:
ggtags.el:1345:22:Warning: reference to free variable `xref--marker-ring'

In ggtags-view-tag-history:
ggtags.el:1388:22:Warning: reference to free variable `xref--marker-ring'
ggtags.el:2367:11:Error: Given parent class xref-file-location is not a class
Makefile:8: recipe for target 'ggtags.elc' failed
make: *** [ggtags.elc] Error 1

I am sorry I don't know what is wrong, it has been a couple of years since I last was deeper into these things and may have forgotten something important.

**Comment by leoliu** [comment]
Are you using `ggtags` from git which requires Emacs >= 25. Use the tagged 0.8.13 version instead for Emacs 24.x.

**Comment by gthaker** [comment]
Sorry about that. I believe this issue (issue #190) should be closed.
