### ISSUE TITLE
I want to know how to use ggtags with Matlab language?

### ISSUE THREAD

**Issue by fu123456** [leoliu/ggtags#192]
Hi,
Gnu global support for Matlab language. Therefore how to config ggtags so that this plugin does work with matlab-mode?

**Comment by leoliu** [comment]
In `matlab-mode`, run `M-x ggtags-mode` and then `M-.` on a symbol and follow from there.

If you want to turn on `ggtags-mode` for `matlab-mode`: `(add-hook 'matlab-mode-hook (lambda () (ggtags-mode 1)))`.

**Comment by fu123456** [comment]
Yes, It seems to does work according to your instruction. But I do "ggtags-show-definition", and it often shows "definition not found". Tags are created as follows: cd <project_home>,  gtags --gtagslabel=pygments. Finding a definition of a function is a task often used by me for most of time.

**Comment by fu123456** [comment]
Thank you. It has done work well.

**Comment by leoliu** [comment]
I am confused. Did you get it to work the way you want?

**Comment by fu123456** [comment]
It does work well. I reinstall the all according to the instructions in
 https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Btags/gtags 
It can support Matlab language well.
