### ISSUE TITLE
can ggtags support something similar to speedbar or EmacsCodeBrowser

### ISSUE THREAD

**Issue by gthaker** [leoliu/ggtags#193]
I was wondering if there is anything like emacs speedbar or emacscodebrowser like support that would w/ with the ggtags gnu_global eco system. Thanks for any pointers.

I seek a side window that shows me definitions in a file along w/ a list of all my files with a "+" sign I can expand to reveal (or hide) definitions for each file. Thanks.

https://www.emacswiki.org/emacs/EmacsCodeBrowser

or 
https://www.emacswiki.org/emacs/SpeedBar

**Comment by leoliu** [comment]
I think if you use `ggtags-build-imenu-index` for `imenu-create-index-function` these packages will be able to at least use `ggtags` for some of their features. Not tested though just guessing.
