### ISSUE TITLE
Should 'ggtags-include-pattern' be a buffer local variable?

### ISSUE THREAD

**Issue by ooglyhLL** [leoliu/ggtags#200]
It seems there are just too many different languages out there, and my impression is that this would be helped by making the variable buffer local. The documentation could be extended accordingly, suggesting that language modes should set this to an appropriate value.

**Comment by leoliu** [comment]
Check the variable in emacs using `C-h v` it's already marked safe to set buffer-local if it's a string.

**Comment by ooglyhLL** [comment]
Yes, thanks. I was thinking that it should actually *be* buffer local in any case. Otherwise many different language modes or user init files would need to include a spell involving `make-variable-buffer-local`.
Regarding the safe as string (only): Looking at the more complex syntax of e.g. Python import statements, or that of some other languages, I'd argue that in many cases the variable will end up being a mode-specific function. WDYT?

**Comment by leoliu** [comment]
Use `setq-local`.

**Comment by ooglyhLL** [comment]
Didn't even know that. We never stop learnig, do we. Thanks.
