### ISSUE TITLE
Is there an option to override project root?

### ISSUE THREAD

**Issue by lyq0930** [leoliu/ggtags#201]
Hi, 

I have projects setup like:
```
~
|--projects
        |--projectA
        |--projectB
```
I generated GTAGS at `~/projects` but have projectile setup for each sub-project `~/projects/projectA` and `~/projects/projectB`.

It seems like ggtags use projectile to find the project root, and it always pointed to those sub projects. Since `ggtags-project-root` is a buffer local variable, I wasn't able to override it by neither `setq` nor project local variable `.dir-locale`. I'm wondering is there a way to override the project root or disable the projectile inferring?

Thanks,
Louie

**Comment by leoliu** [comment]
The project root is normally where `global` considers its project root e.g. `global -pr`.

**Comment by lyq0930** [comment]
Got u, it turned out I didn't delete the G* files in the sub project directory. After deleting them and only keeping the GTAGS, etc files in the root directory, problem solved. Thanks for the help!
