### ISSUE TITLE
ggtags doesn't work with xref in Emacs 27.2 since latest update

### ISSUE THREAD

**Issue by tttuuu888** [leoliu/ggtags#214]
First of all, thanks a lot for this great package. And thank for quick update for Emacs 28 as well.
However ggtags doesn't work with xref in Emacs 27.2 since last update(https://github.com/leoliu/ggtags/commit/1442ab8c7f02d246f14150207534fba4a42201ba).

The error message I see from `xref-find-definitions` and `xref-find-references` is as below:

`cl-no-applicable-method: No applicable method: xref-location-marker, #s(ggtags-xref-location ... ...)`

Thanks.

**Comment by leoliu** [comment]
Thank you very much for the test!
