### ISSUE TITLE
gtags single-update processes initiated by file saves never end

### ISSUE THREAD

**Issue by kaushalmodi** [leoliu/ggtags#83]
Hi,

I recently realized that my machine was hogged up by about a hundred (not using a hyperbole) `gtags -i --single-update FILE PROJ_PATH` processes. Looks like they got initiated every time I saved a file.

But those processes have frozen and are hogging the CPU cycles since last few days.

I even see such processes initiated multiple times for the same file as I must have saved the same file multiple times.

Why would the gtags process get stuck? Any help? Are you able to reproduce this?

I can't say exactly when this started happening; I can say that this started happening some time in last 2-3 weeks.

Currently I am on emacs 24.4 (stable) and the latest version of ggtags.

Thanks.

**Comment by prashks** [comment]
FYI - I ran into this issue as well (note: it was all working fine for me for months on the same source repo).
Updated my `global` to 6.5.4 and still did not fix it.

I ran the `global --single-update <filepath>` from a regular terminal (outside of emacs) and sure enough that just hung (and had launched the gtags process eating up 100% cpu). So, that ruled out emacs for me.

Glad to have found this thread - I tried the `~/.globalrc` confing mentioned above but it still did not resolve it.

Finally removed and rebuilt the gtags database (`GTAGS, GRTAGS, GPATH`) and that solved it !
Looks like global/gtags' database got corrupted.

I've also updated my `global` to 6.5.5.

**Comment by krizex** [comment]
@prashks Thanks, you solved my issue.

**Comment by prashks** [comment]
Glad to hear it resolved your issue @krizex !

**Comment by zhengyangfeng00** [comment]
> Found the problem: The reason by gtags update on file save was freezing was because gtags was trying to look into a huge folder which I should have excluded.
> 
> The problem got fixed after I put this line in my `~/.globalrc` file:
> 
> common:\
>     :skip=HTML/,HTML.pub/,tags,TAGS,ID,y.tab.c,y.tab.h,gtags.files,cscope.files,cscope.out,cscope.po.out,cscope.in.out,SCCS/,RCS/,CVS/,CVSROOT/,{arch}/,autom4te.cache/,*.orig,*.rej,*.bak,*~,#*#,*.swp,*.tmp,*_flymake.*,*_flymake,HUGE_FOLDER/:
> I removed the `ggtags-after-save-function` hack and everything is good now.

May I ask you how did you find which directory was causing the problem?
