### ISSUE TITLE
Too many prompts for ggtags-create-tags

### ISSUE THREAD

**Issue by rdotdk** [leoliu/ggtags#84]
Hi, 
I have been using ggtags for a while. Initially for creating a tag file, if i invoke ggtags-create-tags, i get the following prompts in emacs,
 
1. File GTAGS not found; run gtags? (yes or no)
2. The root directory 
3. use 'ctags' backend? (yes or no).

Is it possible to ignore the prompts 1 and 3. I always choose yes for prompt 1 and 3. So can you tell me how to configure so that i get the only one prompt for choosing the root directory? I don't want to get the other two prompts. I always want to run gtags if not present and yes i want to use ctags by default.

**Comment by tuhdo** [comment]
Possibly we can ignore prompt 1. But for prompt 3, there are people who want to use `gtags` as backend for supported, languages (because clearly it's better than `ctags`). and `ctags` otherwise. It would be inconvenient having to use Elisp to set the default backend again.

**Comment by rdotdk** [comment]
Thanks for your reply @tuhdo . So how can i ignore the first prompt?

**Comment by tuhdo** [comment]
You need to wait for @leoliu to approve and change it.

**Comment by leoliu** [comment]
@rdotdk and @tuhdo,

it sounds like a good idea to merge 1 and 2. I'll take a close look later today.  Thanks for the report.

Leo

**Comment by rdotdk** [comment]
Thanks @tuhdo, @leoliu

**Comment by leoliu** [comment]
I get rid of the yes-or-no question.

**Comment by rdotdk** [comment]
Great!
