### ISSUE TITLE
ido integration with ggtags-find-file

### ISSUE THREAD

**Issue by rdotdk** [leoliu/ggtags#86]
Hi leoliu,

I came across this repo, where tag file generated using etags is integrated with ido, which gives a nice ido completion while finding a new file. Is it possible to do the same with ggtags-find-file? use the tags generated by gtags and integrate it with ido?

Refer: https://github.com/pierre-lecocq/emacs4developers/blob/master/chapters/03-building-your-own-editor.org#files-navigation-aka-fuzzy-matching-with-tags-and-ido

I have already created an issue, but no one seem to respond.
https://github.com/pierre-lecocq/emacs4developers/issues/18

**Comment by leoliu** [comment]
Yes, that is there for a while. See `ggtags-completing-read-function`. Set it to any completing function you like.

**Comment by rdotdk** [comment]
Can you show me how to do that? Here is what i did,
M-x customize-mode ggtags
For Ggtags Completing Read Function : ido-completing-read
Apply and Save.

After that if i invoke M-x ggtags-find-file, i don't get what i expected. Check the below image.

![screenshot from 2015-01-30 20 00 53](https://cloud.githubusercontent.com/assets/3027568/5977109/da06c510-a8ba-11e4-9fc6-2a3e4217f921.png)

**Comment by aethanyc** [comment]
https://github.com/leoliu/ggtags/issues/56#issuecomment-43165031 might help you.

**Comment by rdotdk** [comment]
Works. Thanks @aethanyc. I don't know elisp, so i try to configure using the customize options. Can you tell me what was wrong with the way i did?

**Comment by aethanyc** [comment]
I got the code snippet from @leoliu. I guess the second argument of `ido-completing-read` does not accept `ggtags-completion-table` so it need to be converted to a list of strings by `(all-completions "" ggtags-completion-table)`. I will be great if ggtags could provide a easy option to switch to ido-based find-file though.

**Comment by leoliu** [comment]
hi @rdotdk and @aethanyc,

Yes that is correct. This is due to `ggtags-completion-table`. We used to pipe all the tag names to emacs but that was not fun for large projects such as the linux kernel.

Leo

**Comment by rdotdk** [comment]
Thanks @leoliu . I'll close the issue.
