### ISSUE TITLE
Cannot use helm as ggtags-completing-read-function

### ISSUE THREAD

**Issue by goofansu** [leoliu/ggtags#90]
I enabled `helm-mode` but the `ggtags-completing-read-function` remains the default.

**Comment by leoliu** [comment]
hi @goofansu,

If you want the completing-read function from helm to come through, don't set `ggtags-completing-read-function` or it will shadow `completing-read-function`.

Cheers,
Leo

**Comment by goofansu** [comment]
hi @leoliu,

I didn't set `ggtags-completing-read-function`, just enabled `helm-mode`, but it didn't use the helm completion system.

**Comment by leoliu** [comment]
what's the value of `completing-read-function` when this failed?

**Comment by CuriousSoul** [comment]
I did  describe-variable for ggtags-completing-read-function and I got following output.

```
ggtags-completing-read-function is a variable defined in `ggtags.el'.
Its value is nil

  This variable may be risky if used as a file-local variable.

Documentation:
Ggtags specific `completing-read-function' (which see).
Nil means using the value of `completing-read-function'.

You can customize this variable.

[back]
```

**Comment by goofansu** [comment]
completing-read-function is a variable defined in `minibuffer.el'.
Its value is helm--completing-read-default

  This variable may be risky if used as a file-local variable.

Documentation:
The function called by `completing-read' to do its work.
It should accept the same arguments as `completing-read'.

[back]

**Comment by goofansu** [comment]
completing-read-function is a variable defined in `minibuffer.el'.
Its value is helm--completing-read-default

  This variable may be risky if used as a file-local variable.

Documentation:
The function called by `completing-read' to do its work.
It should accept the same arguments as `completing-read'.

**Comment by leoliu** [comment]
hi @goofansu,

Sorry for my belated reply. Did you find out where the issue is? Look like if you have `ggtags-completing-read-function` set to nil, it should work since `completing-read-function` is set by helm.

HTH,
Leo

**Comment by goofansu** [comment]
Close this issue as I'm using ivy-mode instead of helm now.
