### ISSUE TITLE
switching between GTAGS

### ISSUE THREAD

**Issue by vvv** [leoliu/ggtags#91]
I have two directories, which the same git repository is cloned into. One directory (`~/m/`) has a feature branch checked out, another directory (`~/a/`) — the master branch.

```
~/
 \_ m/
 \_ a/
```

Most of the time I navigate tags in the former directory. But sometimes I need to open a source file in the second directory and navigate the tags there. So I expect ggtags to use the second set of tags — `a/GTAGS`. Unfortunately, when I `M-.` an identifier in `a/` directory, ggtags jumps to the definition in `m/` directory.

Vanilla `gtags-mode` does the right thing in this situation: it jumps to the definition in `a/` directory.

**Comment by vvv** [comment]
This issue might be related to #42.

**Comment by vvv** [comment]
I've come up with a workaround: `(setq ggtags-project-duration 30)`.
It works so far, but I suspect there should be a better solution.

This workaround forces `ggtags-find-project` to [execute](https://github.com/leoliu/ggtags/blob/master/ggtags.el#L533) 'global -pr' command.

**Comment by leoliu** [comment]
hi @vvv,

`global` by default search from current directory upwards to find the GTAGS file. So it will take something else to find it in a sibling directory. Could you see if you have set some of `global` environment variables that may change its behaviour?

`ggtags-find-project` caches its findings buffer-locally until invalidated, which is automatically done If you use `ggtags-create-tags`.

BTW, working with multiple projects is very common in my use of `ggtags`, I'd be surprised to see it broken ;)

Leo

**Comment by vvv** [comment]
I am not able to reproduce this problem any more. No [workaround](https://github.com/leoliu/ggtags/issues/91#issuecomment-77551151) is needed, everything works out of the box.

It might be a case of misconfiguration on my side or something like that. Sorry for the noise.
