### ISSUE TITLE
"C-c M-h" conflicts with erlang-mode's mark-clause

### ISSUE THREAD

**Issue by goofansu** [leoliu/ggtags#92]
I set following but this key is always bind to `ggtags-view-tag-history`, how can I override it?

`(define-key erlang-mode-map (kbd "C-c M-h") 'erlang-mark-clause)`

Thanks

**Comment by leoliu** [comment]
You can remove gates' binding: `(define-key ggtags-mode-map (kbd "C-c M-h") nil)`

**Comment by goofansu** [comment]
Thank you so much :laughing:
