### ISSUE TITLE
Considerable delay when jumping to tags via command-line vs via emacs

### ISSUE THREAD

**Issue by kaushalmodi** [leoliu/ggtags#94]
Hi,

On the command-line (in a terminal outside emacs), if I type `global TAGNAME`, I get the file references instantly.

But if I do it via emacs (`M-x ggtags-show-definition`), it takes a considerable delay (unlike almost instant "find-tag" action using Exuberant ctags): First the compilation buffer launches, then the `global` command is seen executing in that.. it takes about 5-7 seconds and then the results show up.

The whole process of finding tags using `ggtags` is 100% functional; just that it is too slow.

Do you also see a similar behavior (emacs/compile command limitation?) ?

Here is [my `ggtags` setup][1] for reference.

Thanks!

[1]: https://github.com/kaushalmodi/.emacs.d/tree/c2dcf09366629bf7bb7c3ffa82d3fc308bc0789f/setup-files/setup-tags.el#L86

**Comment by leoliu** [comment]
`ggtags-show-definition` should be reasonably fast. Could you provide a recipe to reproduce the bug, starting from `emacs -Q`?

**Comment by kaushalmodi** [comment]
I finally figured out that this delay is because my shell init (tcsh config) takes a long time to load. Looks like that init happen each time a shell command is called my emacs.

I would be great if you can share any info on how to prevent emacs trying to load my shell config each time. But as this issue is not related to gtags, I am closing it.

Thanks.

**Comment by kaushalmodi** [comment]
Here's a solution that worked for me.

I wrapped the stuff in my shell config that shouldn't be needed to be run each time `shell-command` is called in an if condition:

```sh
if ( ! ($?SHELL_CONFIG_LOADED) ) then
 # slow stuff
endif
```

And I put this in my emacs init:

```el
(setenv "SHELL_CONFIG_LOADED" "1")
```
