### ISSUE TITLE
A perhaps less invasive approach

### ISSUE THREAD

**Issue by jwiegley** [leoliu/ggtags#95]
I've found that if I jump to something with `M-.` and then start doing work, and switching buffers, sometimes I'll (seemingly) randomly get flipped to some other buffer while I'm typing.  This is because I forgot to dismiss whatever mode I'm in immediately after jumping to a tag.

I'd prefer it if the behavior were closer to that of regular tags:

 - Hitting `M-.` takes you immediately to the first/best definition.
 - If that's not what you wanted, hitting `C-u M-.` takes you to the next matching identifier, *and then* pops up the window showing all the options and putting you into the special navigation mode.

Because if I need the navigation mode all the time, something is wrong; and if I almost never need it and it's always there and needing me to dismiss it with RET, something else is wrong. :)

Thanks for the great mode!

**Comment by leoliu** [comment]
Hi @jwiegley,

Thanks for the input. I'll think about a way to make this possible ;)

Leo

**Comment by leoliu** [comment]
Hi @jwiegley,

Sorry for my delay. I wonder if `ggtags-enable-navigation-keys` suit your needs. If you set it to nil no navigation key bindings are enabled. so you get a normal compilation-mode popped up full of matched tags. You can navigate to next tag by using the `next-error` command.

Cheers,
Leo

**Comment by jwiegley** [comment]
That sounds like exactly what I need, thanks!
