### ISSUE TITLE
please allow 'global -u' to be overridden (e.g., to allow for additional arguments such as -f)

### ISSUE THREAD

**Issue by seabadger** [leoliu/ggtags#97]
ggtags-update-tags hardcodes the 'global -u' command. 
If the codebase is sufficiently large that running 'global -u' (which indexes everything) takes a long time, ggtags becomes unusable.

In my specific setup, I only need to index a subset of the codebase, so the way I'd normally run global is something along the lines of  'find foo bar baz -type f | grep -e '\.[ch]pp' -e '\.[ch]' ...  > global_file_list; global -u -f global_file_list'.

I can certainly work around the current implementation by writing a wrapper script for global, but I'd prefer to be able to customize this within emacs if possible. Some ideas off the top of my head:
- allow a custom command (or even a function that  runs the global command?) to be specified
- (narrowly solving this issue) allow a filelist (or a function or command to generate it) to be passed in.

**Comment by leoliu** [comment]
Hi @seabadger,

`ggtags` only does `global -u` if the project size is smaller than `ggtags-oversize-limit`, i.e. when running `global -u` is quick. If `global -u` is slow, you need to adjust the threshold by changing `ggtags-oversize-limit`. Could you check if that helps?

Leo

**Comment by seabadger** [comment]
Setting it to 0 does work, but it means that it'll never actually update the index.

To clarify a bit: while I have a large codebase, I only index the small subset that I actively work with; the rest stays unindexed. Thus, the files produced by global are actually fairly small (which is why I had to use an artificially low limit above).

**Comment by seabadger** [comment]
BTW, I had a typo in the original report. The command
  global -u -f
is wrong. It should be
  gtags -i -f list_file
(incremental update, index only files in the specified list_file).

**Comment by leoliu** [comment]
hi @seabadger,

When a project is larger than `ggtags-oversize-limit`, the index is updated on save and only for the modified file. This should be pretty quick. I tested on the linux kernel without any problems.

HTH,
Leo

**Comment by leoliu** [comment]
Hi @seabadger,

Let me know if you still want to make "global -u" customisable? - Leo

**Comment by seabadger** [comment]
Actually, turns out global itself can support what I need: according to the docs, I can have a whitelist of files to be indexed called "global.files" (sitting in the same dir as the GTAGS, etc), and any invocation of global will implicitly use that.

So looks like my use case is taken care of without the need to change ggtags :) We can close this request.

Thanks for ggtags, and especially for being responsive! I really appreciate it.

**Comment by leoliu** [comment]
Hi @seabadger,

See also the doc-string of `ggtags-create-tags` which mentions `gtags.files`.

 Leo
